name = "SphereEversion"
defaultTargets = ["SphereEversion"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
linter.mathlibStandardSet = true
linter.flexible = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[lean_lib]]
name = "SphereEversion"
